
# tap repositories and their packages

tap homebrew/core
brew anyenv
brew aom
brew apr
brew apr-util
brew argon2
brew aribb24
brew aspell
brew autoconf
brew automake
brew bash
brew bison
brew brew-gem
brew brotli
brew bzip2
brew ca-certificates
brew cairo
brew carthage
brew cask
brew certifi
brew cjson
brew coreutils
brew curl
brew dav1d
brew direnv
brew docker
brew docker-completion
brew docutils
brew emacs
brew emojify
brew exiftool
brew ffmpeg
brew flac
brew fontconfig
brew freetds
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gcc
brew gd
brew gettext
brew gh
brew giflib
brew glib
brew glow
brew gmp
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew grep
brew harfbuzz
brew highway
brew hub
brew hugo
brew icu4c@76
brew icu4c@77
brew imath
brew isl
brew jansson
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew jq
brew krb5
brew lame
brew leptonica
brew less
brew libarchive
brew libass
brew libassuan
brew libassuan@2
brew libavif
brew libb2
brew libbluray
brew libdeflate
brew libedit
brew libevent
brew libgcrypt
brew libgpg-error
brew libiconv
brew libidn2
brew libksba
brew libmicrohttpd
brew libmpc
brew libnghttp2
brew libogg
brew libpng
brew libpq
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtommath
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libyaml
brew libzip
brew little-cms2
brew lpeg
brew luajit
brew luv
brew lz4
brew lzo
brew m4
brew mackup
brew mariadb-connector-c
brew mas
brew mbedtls
brew mpdecimal
brew mpfr
brew mpg123
brew mydumper
brew navi
brew ncurses
brew neovim
brew nettle
brew npth
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew php@8.2
brew pinentry
brew pinentry-mac
brew pixman
brew pkg-config
brew python-packaging
brew python@3.12
brew python@3.13
brew rav1e
brew re2c
brew readline
brew rtmpdump
brew rubberband
brew sdl2
brew snappy
brew speex
brew sqlite
brew srt
brew ssh-copy-id
brew svt-av1
brew tbls
brew tcl-tk
brew terminal-notifier
brew tesseract
brew theora
brew tidy-html5
brew tmux
brew trash
brew tree
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew utf8proc
brew wakatime-cli
brew webp
brew wget
brew x264
brew x265
brew xorgproto
brew xvid
brew xz
brew yt-dlp
brew zeromq
brew zimg
brew zlib
brew zoxide
brew zstd

tap homebrew/cask
cask 1password
cask 1password-cli
cask appcleaner
cask applepi-baker
cask arq
cask avast-security
cask blobsaver
cask brave-browser
cask brooklyn
cask coteditor
cask cursor
cask docker
cask dropbox
cask font-fira-code
cask font-fontawesome
cask font-hack-nerd-font
cask font-jetbrains-mono
cask font-jetbrains-mono-nerd-font
cask ghostty
cask gpg-suite
cask homerow
cask iterm2
cask itsycal
cask jordanbaird-ice
cask karabiner-elements
cask keybase
cask klogg
cask leader-key
cask makemkv
cask notion
cask obsidian
cask popclip
cask qlmarkdown
cask qlstephen
cask qlvideo
cask raycast
cask setapp
cask subler
cask sublime-text
cask superslicer
cask syntax-highlight
cask tower
cask transmit
cask typora
cask visual-studio-code
cask zen-browser

tap homebrew/bundle

tap 1password/tap

tap argon/mas

tap beeftornado/rmtree

tap dzirtusss/tap

tap eddieantonio/eddieantonio

tap k1low/tap

tap knqyf263/pet
brew pet

tap px4/px4

tap qmk/qmk

tap rcmdnk/file
brew brew-file

tap vitorgalvao/tiny-scripts

tap vladdoster/formulae

# App Store applications
appstore 1569813296 1Password for Safari (8.10.56)
appstore 302584613 Amazon Kindle (7.24)
appstore 425264550 Blackmagic Disk Speed Test (3.4.2)
appstore 1518425043 Boop (1.4.0)
appstore 1432182561 Cascadea (2.1.3)
appstore 1024640650 CotEditor (4.5.4)
appstore 1055511498 Day One (2025.1.1)
appstore 640199958 Developer (10.7.1)
appstore 549083868 Display Menu (2.2.5)
appstore 1526651672 Eagle for Safari (3.1.9)
appstore 424389933 Final Cut Pro (11.0)
appstore 1544743900 Hush (1.0.17)
appstore 408981434 iMovie (10.4.3)
appstore 288545208 Instapaper (9.1.2)
appstore 422293948 IP Scanner Home (5.05)
appstore 1142151959 JustFocus (2.2.4)
appstore 539883307 LINE (9.5.0)
appstore 441258766 Magnet (3.0.6)
appstore 1505432629 NotePlan (3.17.3)
appstore 409203825 Numbers (14.3)
appstore 992700627 Omoidebako (3.0)
appstore 1547106997 Pins (2022.2)
appstore 866773894 Quiver (3.2.7)
appstore 1549370672 Save to Raindrop.io (5.6.71)
appstore 803453959 Slack (4.41.105)
appstore 1176895641 Spark (2.11.47)
appstore 904280696 Things3 (3.21.4)
appstore 1289119450 URL Linker (1.1)
appstore 1480933944 Vimari (2.1.1)
appstore 1584519802 Vimlike (1.5.3)
appstore 1295203466 Windows App (11.0.9)
appstore 497799835 Xcode (16.2)
