
# tap repositories and their packages

tap homebrew/core
brew brotli
brew ca-certificates
brew curl
brew docker
brew giflib
brew jpeg-turbo
brew libnghttp2
brew libnghttp3
brew libngtcp2
brew libpng
brew libpsl
brew libssh2
brew libtiff
brew lz4
brew mackup
brew mas
brew mpdecimal
brew navi
brew openssl@3
brew python@3.14
brew readline
brew sqlite
brew webp
brew xz
brew zstd

tap homebrew/cask
cask 1password
cask 1password-cli
cask appcleaner
cask arq
cask avast-security
cask blobsaver
cask brave-browser
cask chatgpt
cask choosy
cask claude
cask claude-code
cask coteditor
cask cursor
cask docker
cask dropbox
cask font-fira-code
cask font-fontawesome
cask font-hack-nerd-font
cask font-jetbrains-mono
cask font-jetbrains-mono-nerd-font
cask gpg-suite
cask heptabase
cask iterm2
cask itsycal
cask jordanbaird-ice
cask karabiner-elements
cask klogg
cask leader-key
cask makemkv
cask ngrok
cask notion
cask obsidian
cask popclip
cask prusaslicer
cask qlmarkdown
cask raycast
cask setapp
cask subler
cask sublime-text
cask syntax-highlight
cask tower
cask transmit
cask typora
cask visual-studio-code
cask zen-browser

tap 1password/tap

tap argon/mas

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1569813296 1Password for Safari (8.12.29)
appstore 425264550 Blackmagic Disk Speed Test (3.4.3)
appstore 1438243180 Dark Reader for Safari (2.1.10)
appstore 1055511498 Day One (2026.16)
appstore 1435957248 Drafts (53.0)
appstore 1526651672 Eagle for Safari (3.1.20)
appstore 424389933 Final Cut Pro (12.3)
appstore 1571234297 Fokus (1.8)
appstore 422293948 IP Scanner Home (5.05)
appstore 1622835804 Kagi for Safari (2.2.3)
appstore 1547106997 Pins (2024.1)
appstore 1640236961 Save to Reader (0.17.5)
appstore 803453959 Slack (4.51.185)
appstore 904280696 Things3 (3.22.13)
appstore 1289119450 URL Linker (1.1)
appstore 497799835 Xcode (26.6)
