#!/bin/bash

trap 'echo Error: $0: stopped' ERR
set -u
set -e

if ! type brew >/dev/null 2>&1; then
    echo 'Requirement: brew' 1>&2
    exit 1
fi

echo 'brew updating...'

brew update
outdated=$(brew outdated)

if [ -n "$outdated" ]; then
    echo 'The following package(s) will upgrade.'
    echo ''
    echo "$outdated"
    echo 'Are you sure?'
    echo 'If you do not want to upgrade, please type Ctrl-c now.'
    echo ''

    # Wait Ctrl-c
    read dummy

    brew upgrade
fi

declare -a BREW_PACKAGES=(
  "autoconf"
  "automake"
  "caskroom/cask/brew-cask"
  "coreutils"
  "imagemagick"
  "mysql"
  "pandoc"
  "pkg-config"
  "reattach-to-user-namespace"
  "terminal-notifier"
  "tmux"
  "trash"
  "wget"
)

for package in "${BREW_PACKAGES[@]}"
do
    if brew list -1 | grep -q "^$(basename $package)"; then
        echo "Skip: brew install ${package}"
    else
        brew install $package
    fi
done