[user]
	name = monta
	email = djmonta@gmail.com
	signingkey = 51F3E100AC4B30813F9AF72CFA019D34F1DD8BC7
[commit]
	gpgsign = true
	template = ~/dotfiles/.config/git/.gittemplate
[gpg]
	program = /usr/local/MacGPG2/bin/gpg2
[mergetool]
	keepBackup = true
	prompt = false
[color]
	ui = true
[core]
	excludesfile = ~/dotfiles/.config/git/.gitignore.default
	quotepath = false
[i18n]
	logoutputencoding = utf-8
	commitencoding = utf-8
