
# tap repositories and their packages

tap homebrew/core
brew adns
brew aom
brew apr
brew apr-util
brew autoconf
brew automake
brew awscli
brew bison
brew boost
brew cairo
brew cask
brew coreutils
brew czmq
brew direnv
brew emacs
brew emojify
brew ffmpeg
brew flac
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gd
brew gdbm
brew gettext
brew giflib
brew glib
brew gmp
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew handbrake
brew harfbuzz
brew highlight
brew icu4c
brew ilmbase
brew imagemagick
brew imagemagick@6
brew isl
brew jasper
brew jpeg
brew jq
brew lame
brew leptonica
brew less
brew libass
brew libassuan
brew libbluray
brew libde265
brew libebml
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libgphoto2
brew libheif
brew libicns
brew libidn2
brew libksba
brew libmagic
brew libmatroska
brew libmpc
brew libogg
brew libomp
brew libpng
brew libressl
brew libsamplerate
brew libsass
brew libsndfile
brew libsodium
brew libsoxr
brew libspiro
brew libtasn1
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libusb
brew libusb-compat
brew libvidstab
brew libvorbis
brew libvpx
brew libxml2
brew libzip
brew little-cms2
brew lua
brew lz4
brew lzo
brew mackup
brew makedepend
brew mas
brew mcrypt
brew mercurial
brew mhash
brew mkvtoolnix
brew mp4v2
brew mpfr
brew mysql
brew net-snmp
brew nettle
brew node
brew npth
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openssl
brew openssl@1.1
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew perl
brew pinentry
brew pinentry-mac
brew pixman
brew pkg-config
brew postgresql
brew pth
brew python
brew python@2
brew re2c
brew readline
brew reattach-to-user-namespace
brew rtmpdump
brew rubberband
brew sane-backends
brew sdl2
brew shared-mime-info
brew snappy
brew speex
brew sqlite
brew ssh-copy-id
brew terminal-notifier
brew terraform
brew tesseract
brew tesseract-lang
brew theora
brew trash
brew unbound
brew unixodbc
brew utf8proc
brew webp
brew wget
brew wxmac
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl
brew zeromq

tap homebrew/cask-fonts
cask font-fira-code
cask font-hack-nerd-font
cask font-source-han-sans

tap homebrew/cask-versions

tap homebrew/cask
cask 1password
cask alfred
cask applepi-baker
cask cmd-eikana
cask dropbox
cask google-chrome
cask iterm2
cask java
cask qlcolorcode
cask qlmarkdown
cask qlvideo
cask sublime-text
cask transmit
cask visual-studio-code

tap argon/mas

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask adobe-creative-cloud
cask appcleaner
cask bartender
cask docker
cask font-fontawesome
cask font-source-han-code-jp
cask ibackup
cask itsycal
cask kindle
cask qlimagesize
cask qlstephen
cask sequel-pro
cask tower
cask tweeten

# App Store applications
appstore 422293948 com.10baseT.IPScannerHomeMac (3.91)
appstore 497799835 com.apple.dt.Xcode (11.0)
appstore 409183694 com.apple.iWork.Keynote (9.2)
appstore 409203825 com.apple.iWork.Numbers (6.2)
appstore 1055511498 com.bloombuilt.dayone-mac (4.2.0)
appstore 1432182561 com.cascadea.app (1.4.2)
appstore 1024640650 com.coteditor.CotEditor (3.7.8)
appstore 441258766 com.crowdcafe.windowmagnet (2.4.4)
appstore 904280696 com.culturedcode.ThingsMac (3.9.2)
appstore 873245660 com.ddeville.spillo (2.0)
appstore 866773894 com.happenapps.Quiver (3.2.7)
appstore 1107421413 com.khanov.BlockerMac (1.4.8)
appstore 445189367 com.pilotmoon.popclip (2019.9.1)
appstore 1176895641 com.readdle.smartemail-Mac (2.3.12)
appstore 568494494 com.readitlater.PocketMac (1.8.4)
appstore 1145215534 com.rimbunesia.osx.Kelir (1.5)
appstore 1084713122 com.thoughtbot.Markoff (1.0.1)
appstore 803453959 com.tinyspeck.slackmacgap (4.1.0)
appstore 549083868 de.milchimgemuesefach.Display-Menu (2.2.3)
appstore 992700627 jp.buffalo.OmoidebakoMac (2.5)
appstore 539883307 jp.naver.line.mac (5.19.0)
appstore 1142151959 me.justinyan.justfocus (1.6.4)
appstore 848311469 me.tanmay.WriteMac (1.1.8)
appstore 961656759 net.doublerew.Timeline (1.0)
