
# tap repositories and their packages

tap homebrew/core
brew adns
brew apr
brew apr-util
brew autoconf
brew automake
brew awscli
brew bison
brew boost
brew cairo
brew cask
brew coreutils
brew czmq
brew direnv
brew emacs
brew emojify
brew ffmpeg
brew flac
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew fzf
brew gd
brew gdbm
brew gettext
brew glib
brew gmp
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew handbrake
brew harfbuzz
brew highlight
brew icu4c
brew imagemagick
brew imagemagick@6
brew isl
brew jasper
brew jpeg
brew jq
brew lame
brew less
brew libassuan
brew libebml
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libgphoto2
brew libicns
brew libidn2
brew libksba
brew libmagic
brew libmatroska
brew libmpc
brew libogg
brew libpng
brew libressl
brew libsass
brew libsodium
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libusb-compat
brew libvorbis
brew libvpx
brew libxml2
brew libzip
brew little-cms2
brew lua
brew lz4
brew mackup
brew makedepend
brew mas
brew mcrypt
brew mercurial
brew mhash
brew mkvtoolnix
brew mp4v2
brew mpfr
brew mysql
brew net-snmp
brew nettle
brew node
brew npth
brew oniguruma
brew openjpeg
brew openssl
brew openssl@1.1
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew perl
brew pinentry
brew pinentry-mac
brew pixman
brew pkg-config
brew postgresql
brew pth
brew python
brew python@2
brew re2c
brew readline
brew reattach-to-user-namespace
brew sane-backends
brew sdl2
brew snappy
brew sqlite
brew ssh-copy-id
brew terminal-notifier
brew terraform
brew theora
brew trash
brew unixodbc
brew utf8proc
brew webp
brew wget
brew wxmac
brew x264
brew x265
brew xvid
brew xz
brew zeromq

tap homebrew/cask-fonts
cask font-fira-code
cask font-hack-nerd-font
cask font-source-han-sans

tap homebrew/cask-versions
cask java8

tap homebrew/cask
cask 1password
cask alfred
cask applepi-baker
cask cmd-eikana
cask dropbox
cask google-chrome
cask iterm2
cask kindle
cask qlmarkdown
cask qlvideo
cask sublime-text
cask transmit

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew heroku

# Other Cask applications
cask adobe-creative-cloud
cask appcleaner
cask bartender
cask docker
cask font-fontawesome
cask font-source-han-code-jp
cask ibackup
cask java
cask qlcolorcode
cask qlimagesize
cask qlstephen
cask sequel-pro
cask tower
cask visual-studio-code

# App Store applications
appstore 948176063 Boom 2 (1.6.6)
appstore 1024640650 CotEditor (3.6.11)
appstore 1055511498 Day One (2.9.2)
appstore 695406827 Dropzone 3 (3.7.0)
appstore 408981434 iMovie (10.1.10)
appstore 422293948 IP Scanner Home (3.70)
appstore 1142151959 JustFocus (1.6.1)
appstore 1145215534 Kelir (1.5)
appstore 409183694 Keynote (8.3)
appstore 539883307 LINE (5.12.1)
appstore 441258766 Magnet (2.4)
appstore 1084713122 Markoff (1.0.1)
appstore 1137020764 NotePlan (1.6.30)
appstore 409203825 Numbers (5.3)
appstore 992700627 Omoidebako (2.5)
appstore 409201541 Pages (7.3)
appstore 568494494 Pocket (1.8.1)
appstore 445189367 PopClip (1.5.8)
appstore 866773894 Quiver (3.2.3)
appstore 819348619 Revisions (3.0.1)
appstore 803453959 Slack (3.3.3)
appstore 1176895641 Spark (2.1.4)
appstore 873245660 Spillo (2.0)
appstore 904280696 Things3 (3.8)
appstore 961656759 Timeline (1.0)
appstore 1384080005 Tweetbot (3.2)
appstore 485812721 TweetDeck (3.9.889)
appstore 497799835 Xcode (10.1)
