
# tap repositories and their packages

tap homebrew/core
brew adns
brew aom
brew apr
brew apr-util
brew autoconf
brew automake
brew awscli
brew cairo
brew cask
brew coreutils
brew direnv
brew emacs
brew emojify
brew ffmpeg
brew flac
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gdbm
brew gettext
brew giflib
brew glib
brew gmp
brew gnupg
brew gnutls
brew go
brew graphite2
brew harfbuzz
brew highlight
brew hr
brew hub
brew icu4c
brew jpeg
brew lame
brew leptonica
brew less
brew libass
brew libassuan
brew libbluray
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libogg
brew libpng
brew libsamplerate
brew libsndfile
brew libsoxr
brew libspiro
brew libtasn1
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libusb
brew libusb-compat
brew libvidstab
brew libvorbis
brew libvpx
brew little-cms2
brew lua
brew lzo
brew mackup
brew mas
brew ncurses
brew nettle
brew node
brew npth
brew opencore-amr
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew pango
brew pcre
brew pinentry
brew pinentry-mac
brew pixman
brew pkg-config
brew python
brew readline
brew reattach-to-user-namespace
brew rtmpdump
brew rubberband
brew sdl2
brew snappy
brew speex
brew sqlite
brew ssh-copy-id
brew terminal-notifier
brew tesseract
brew tesseract-lang
brew theora
brew tmux
brew unbound
brew webp
brew wget
brew x264
brew x265
brew xvid
brew xz
brew youtube-dl

tap homebrew/cask-fonts
cask font-fira-code
cask font-hack-nerd-font

tap homebrew/cask-versions
cask sequel-pro-nightly

tap homebrew/cask
cask 1password
cask alfred
cask appcleaner
cask cmd-eikana
cask docker
cask dynalist
cask google-chrome
cask ibackup
cask itsycal
cask qlcolorcode
cask qlmarkdown
cask qlvideo
cask tower
cask tweeten
cask visual-studio-code

tap beeftornado/rmtree

tap rcmdnk/file
brew brew-file

tap vitorgalvao/tiny-scripts
brew cask-repair

# Other Cask applications
cask adobe-creative-cloud
cask android-sdk
cask bartender
cask cyberduck
cask dropbox
cask font-fontawesome
cask font-source-han-code-jp
cask gpg-suite
cask iterm2
cask kindle
cask qlimagesize
cask qlstephen
cask sublime-text
cask transmit
cask typora

# App Store applications
appstore 1107421413 1Blocker (1.4.8)
appstore 955155151 Aspect Ratio Calculator (1.3)
appstore 1432182561 Cascadea (1.4.4)
appstore 1024640650 CotEditor (3.8.4)
appstore 1055511498 Day One (4.2.3)
appstore 549083868 Display Menu (2.2.3)
appstore 422293948 IP Scanner (3.91)
appstore 1142151959 Just Focus (1.6.6)
appstore 1145215534 Kelir (1.5)
appstore 409183694 Keynote (9.2)
appstore 539883307 LINE (5.20.1)
appstore 441258766 Magnet (2.4.5)
appstore 1084713122 Markoff (1.0.1)
appstore 409203825 Numbers (6.2)
appstore 568494494 Pocket (1.8.5)
appstore 445189367 PopClip (2019.9.1)
appstore 866773894 Quiver (3.2.7)
appstore 803453959 Slack (4.1.2)
appstore 1176895641 Spark (2.3.14)
appstore 873245660 Spillo (2.0)
appstore 904280696 Things (3.10.1)
appstore 961656759 Timeline (1.0)
appstore 1151308717 traumbaum (1.23)
appstore 899972312 WordService (2.8.2)
appstore 848311469 Write (1.1.8)
appstore 497799835 Xcode (11.2)
appstore 992700627 おもいでばこ (2.5)
